Cleanup some shellcheck warnings

diff --git a/_make_links b/_make_links
--- a/_make_links
+++ b/_make_links
@@ -8,7 +8,7 @@ die() {
 }
 
 verbose () {
-    [ "$VERBOSE" = "yes" ] && echo "$@"    
+    [ "$VERBOSE" = "yes" ] && echo "$@"
 }
 
 debug() {
@@ -16,7 +16,7 @@ debug() {
     [ -z "$DEBUG" ] && "$@"
 }
 
-args=`getopt dv $*`
+args=$(getopt dv "$*")
 if [ $? != 0 ]; then
     die "Usage: $0 [-d] [-v]"
 fi
@@ -45,19 +45,19 @@ if [ "$DEBUG" = "yes" ]; then
     echo
 fi
 
-cd $DOT_DIR
+cd $DOT_DIR || die "Failed to cd into '$DOT_DIR'!"
 
-for file in `ls | egrep -v ^\(_\|\#\)`; do
+for file in $(ls | egrep -v ^\(_\|\#\)); do
     dest=${HOME}/.${file}
 
-    if [ -L $dest ]; then
+    if [ -L "$dest" ]; then
         verbose "# ${dest} is already a symlink... skipping."
         continue
     fi
-    
+
     if [ -e $dest ]; then
         debug mv $dest ${dest}.bak
     fi
 
-    debug ln -s ${DOT_DIR}/$file $dest
+    debug ln -sv "${DOT_DIR}/$file" "$dest"
 done
